spring:
  application:
    name: Lancer
  datasource:
    url: jdbc:h2:mem:lancer
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
